name: echopype
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - ipykernel
  # Keep the version to the latest release
  - echopype==0.8.1
  - s3fs
  - geopandas
  - cartopy
  - numba # Helps ensure a recent version is installed
  # -- holoviz --
  - datashader
  - holoviews
  - hvplot
